"""
C  INITIALISE THE DWARVES.  DLOC IS LOC OF DWARVES, HARD-WIRED IN.  ODLOC IS
C  PRIOR LOC OF EACH DWARF, INITIALLY GARBAGE.  DALTLC IS ALTERNATE INITIAL LOC
C  FOR DWARF, IN CASE ONE OF THEM STARTS OUT ON TOP OF THE ADVENTURER.  (NO 2
C  OF THE 5 INITIAL LOCS ARE ADJACENT.)  DSEEN IS TRUE IF DWARF HAS SEEN HIM.
C  DFLAG CONTROLS THE LEVEL OF ACTIVATION OF ALL THIS:
C	0	NO DWARF STUFF YET (WAIT UNTIL REACHES HALL OF MISTS)
C	1	REACHED HALL OF MISTS, BUT HASN'T MET FIRST DWARF
C	2	MET FIRST DWARF, OTHERS START MOVING, NO KNIVES THROWN YET
C	3	A KNIFE HAS BEEN THROWN (FIRST SET ALWAYS MISSES)
C	3+	DWARVES ARE MAD (INCREASES THEIR ACCURACY)
C  SIXTH DWARF IS SPECIAL (THE PIRATE).  HE ALWAYS STARTS AT HIS CHEST'S
C  EVENTUAL LOCATION INSIDE THE MAZE.  THIS LOC IS SAVED IN CHLOC FOR REF.
C  THE DEAD END IN THE OTHER MAZE HAS ITS LOC STORED IN CHLOC2.

KNFLOC	0 IF NO KNIFE HERE, LOC IF KNIFE HERE, -1 AFTER CAVEAT
DKILL	NUMBER OF DWARVES KILLED (UNUSED IN SCORING, NEEDED FOR MSG)

"""


class Dwarf:
    def __init__(self, loc, is_pirate=False):
        self.loc = loc
        self.is_pirate = is_pirate
        self.old_loc = None
        self.seen = False
        self.alive = True


dwarves_info = [
    ('hall_of_mountain_king', False),
    ('fissure_west', False),
    ('y2', False),
    ('twisty_maze_3', False),
    ('complex_junction', False),
    ('dead_end_3', True),
]

#   CHLOC=114
# 	CHLOC2=140
# 	DLOC(1)=19
# 	DLOC(2)=27
# 	DLOC(3)=33
# 	DLOC(4)=44
# 	DLOC(5)=64
# 	DLOC(6)=CHLOC
# 	DALTLC=18

KNFLOC=0
DKILL=0
